### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by FabianSchmick** [Sibyx/phpGPX#47]
Hey there, first I wanted to say thank you for this really nice library. 

I noticed that the master branch is about 34 commits ahead as the last tagged version (1.0-RC5).
Could please tag a new version so we can have all the new features and bug fixes from the master branch?

**Comment by Sibyx** [comment]
Hi @FabianSchmick 
sorry for such late response, i will try to create tag this week after fixing tests in master branch. I am thinking of releasing new tag as 1.0.0, because I would like to create 2.x version only compatible with PHP 7.x which will be rebuilded from scratch (I regret some architectonical decisions made in 1.x).

**Comment by FabianSchmick** [comment]
Hey @Sibyx any updates on when you could publish a new version?

**Comment by Sibyx** [comment]
Hi @FabianSchmick ,
I am waiting for #45 to merge and `1.0` will be released.
